### ISSUE TITLE
When will you add android?

### ISSUE THREAD

**Issue by KULTI1995** [tyson90/react-native-przelewy24-payment#1]
Important ! When will you add android? :)

**Comment by tyson90** [comment]
Hi, currently we are working on completing iOS version of our app, where p24 payment is used.
Then we will start working on Android version.

So it will probably be added in May or June.

**Comment by KULTI1995** [comment]
:(

**Comment by tyson90** [comment]
The Android base implementation has just landed :)
We also updated [the npm version](https://www.npmjs.com/package/react-native-przelewy24-payment).
